import { H1, H2, H3, H4, H5, H6 } from '../lib/components/Header'

export const STRING_HEADINGS = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']

export const BLOCK_NODES = [
  'div',
  'p',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'table',
  'tbody',
  'tr',
  'th',
  'td',
  ...STRING_HEADINGS,
]

export const NO_END_NODES = ['br', 'input', 'img', 'hr', 'meta']

export const FUNC_HEADINGS = [H1, H2, H3, H4, H5, H6]

export const TABLE_OF_CONTENTS_PLACEHOLDER =
  '\n' + Math.random().toString(32).slice(2) + '\n'

// HTML elements: native camelCase attributes with more than one word
const htmlCamelAttrs = [
  'acceptCharset',
  'accessKey',
  'allowFullScreen',
  'allowTransparency',
  'autoComplete',
  'autoFocus',
  'cellPadding',
  'cellSpacing',
  'charSet',
  'className',
  'contentEditable',
  'contextMenu',
  'crossOrigin',
  'dateTime',
  'defaultChecked',
  'defaultValue',
  'enterKeyHint',
  'formAction',
  'formEncType',
  'formMethod',
  'formNoValidate',
  'formTarget',
  'hrefLang',
  'inputMode',
  'keyParams',
  'keyType',
  'marginHeight',
  'marginWidth',
  'maxLength',
  'mediaGroup',
  'minLength',
  'noValidate',
  'readOnly',
  'rowSpan',
  'colSpan',
  'referrerPolicy',
  'spellCheck',
  'srcDoc',
  'srcLang',
  'srcSet',
  'tabIndex',
  'useMap',
]

// SVG elements: native camelCase attributes with more than one word
const svgCamelAttrs = [
  'accentHeight',
  'alignmentBaseline',
  'allowReorder',
  'arabicForm',
  'baselineShift',
  'baseProfile',
  'capHeight',
  'clipPathUnits',
  'clipPath',
  'colorInterpolation',
  'colorInterpolationFilters',
  'colorProfile',
  'colorRendering',
  'contentScriptType',
  'contentStyleType',
  'diffuseConstant',
  'dominantBaseline',
  'enableBackground',
  'externalResourcesRequired',
  'fillOpacity',
  'fillRule',
  'floodColor',
  'floodOpacity',
  'fontFamily',
  'fontSize',
  'fontSizeAdjust',
  'fontStretch',
  'fontStyle',
  'fontVariant',
  'fontWeight',
  'glyphOrientationHorizontal',
  'glyphOrientationVertical',
  'glyphRef',
  'gradientTransform',
  'gradientUnits',
  'horizAdvX',
  'horizOriginX',
  'imageRendering',
  'keyPoints',
  'keySplines',
  'keyTimes',
  'lengthAdjust',
  'letterSpacing',
  'limitingConeAngle',
  'markerEnd',
  'markerHeight',
  'markerMid',
  'markerStart',
  'markerUnits',
  'markerWidth',
  'maskContentUnits',
  'maskUnits',
  'numOctaves',
  'overlinePosition',
  'overlineThickness',
  'paintOrder',
  'pathLength',
  'patternContentUnits',
  'patternTransform',
  'patternUnits',
  'pointsAtX',
  'pointsAtY',
  'pointsAtZ',
  'preserveAlpha',
  'preserveAspectRatio',
  'primitiveUnits',
  'refX',
  'refY',
  'repeatCount',
  'repeatDur',
  'requiredExtensions',
  'requiredFeatures',
  'shapeRendering',
  'specularConstant',
  'specularExponent',
  'spreadMethod',
  'startOffset',
  'stdDeviation',
  'stitchTiles',
  'stopColor',
  'stopOpacity',
  'strikethroughPosition',
  'strikethroughThickness',
  'strokeDasharray',
  'strokeDashoffset',
  'strokeLinecap',
  'strokeLinejoin',
  'strokeMiterlimit',
  'strokeOpacity',
  'strokeWidth',
  'surfaceScale',
  'systemLanguage',
  'tableValues',
  'targetX',
  'targetY',
  'textAnchor',
  'textDecoration',
  'textLength',
  'textRendering',
  'transformOrigin',
  'underlinePosition',
  'underlineThickness',
  'unicodeBidi',
  'unicodeRange',
  'unitsPerEm',
  'vAlphabetic',
  'vHanging',
  'vIdeographic',
  'vMathematical',
  'vectorEffect',
  'vertAdvY',
  'vertOriginX',
  'vertOriginY',
  'viewBox',
  'wordSpacing',
  'writingMode',
  'xChannelSelector',
  'xHeight',
  'yChannelSelector',
  'zoomAndPan',
]

export const camelAttrs = [...htmlCamelAttrs, ...svgCamelAttrs]

// JSX prop name to HTML attribute name
export const propNameMap = {
  className: 'class',
}

export const namespacePrefixes = ['xmlns', 'xml', 'xlink']
